//vsphere vars
variable "vcenter_username" {
  type    = string
  default = ""
}
variable "vcenter_password" {
  type    = string
  default = ""
}
variable "vcenter_server" {
  type    = string
  default = ""
}
variable "vcenter_cluster" {
  type    = string
  default = ""
}
variable "vcenter_datastore" {
  type    = string
  default = ""
}
variable "vcenter_folder" {
  type    = string
  default = ""
}
variable "vcenter_network" {
  type    = string
  default = "VM Network"
}
variable "convert_template" {
  type    = bool
  default = true
}
variable "insecure_connection" {
  type    = bool
  default = false
}

//iso vars
variable "iso_checksum" {
  type    = string
  default = "sha256:PutChecksumHere"
}
variable "iso_url" {
  type    = string
  default = ""
}
variable "iso_path" {
  type    = string
  default = "ISO/VMware-VMvisor-Installer-201912001-15160138.x86_64.iso"
}

//vm specs
variable "name" {
  type    = string
  default = "ESXi-6.7"
}
variable "cpus" {
  type    = number
  default = 2
}
variable "cpu_cores" {
  type = number
  default = 2
}
variable "memory" {
  type    = number
  default = 4096
}
variable "disk_size" {
  type    = number
  default = 10000
}

//other vars
variable "http_directory" {
  type = string
  default = "./http"
}
variable "ssh_password" {
  type = string
  default = "esxiroot"
}

source "vsphere-iso" "autogenerated_1" {
  //vcenter configuration
  username       = "${var.vcenter_username}"
  password         = "${var.vcenter_password}"
  vcenter_server = "${var.vcenter_server}"
  cluster             = "${var.vcenter_cluster}"
  convert_to_template = "${var.convert_template}"
  datastore           = "${var.vcenter_datastore}"
  folder              = "${var.vcenter_folder}"
  guest_os_type       = "vmkernel65Guest"
  notes = "${formatdate("MMM DD YYYY hh:mm ZZZ","${timestamp()}")}"
  insecure_connection = "${var.insecure_connection}"

  //vm configuration
  NestedHV = "true"
  vm_name        = "${var.name}"
  CPUs                = "${var.cpus}"
  cpu_cores = "${var.cpu_cores}"
  RAM              = "${var.memory}"
  cdrom_type = "sata"
  network_adapters {
    network      = "${var.vcenter_network}"
    network_card = "vmxnet3"
  }
  disk_controller_type = ["lsilogic"]
  storage {
    disk_size = "${var.disk_size}"
    disk_thin_provisioned = true
  }

  //ssh configuration
  #ssh password is set in the user-data yaml file which is used for the OS install
  #a different password can be generated and replaced in the yaml file, however
  #it will be easier to just change the password for the ubuntu user once the VM
  #is officially provisioned
  ssh_password     = "${var.ssh_password}"
  ssh_timeout      = "30m"
  ssh_username     = "root"

  http_directory      = "${var.http_directory}"

  //iso configuration
  #to prevent the need to download the iso all the time, i placed the iso
  #in my datastore in my vsphere environment and used it for the template build.
  #if you want to download and attach the iso independent of vsphere,
  #ensure that you comment or remove the iso_paths line and uncomment
  #the iso_url and iso_checksum lines
  #iso_checksum        = "${var.iso_checksum}"
  #iso_url             = "${var.iso_url}"
  iso_paths = ["[${var.vcenter_datastore}] ${var.iso_path}"]
  
  //boot configuration
  boot_wait           = "3s"
  boot_command        = [
    "<enter>",
    "<wait3s>",
    "<leftshifton>o<leftshiftoff>",
    " netdevice=vmnic0 bootproto=dhcp ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/esxi-kickstart.cfg",
    "<enter>"
  ]
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]
}